Refactor visualization functions
bsc-quantic/OptimizedEinsum.jl pull request #28
Opened 2023-02-06 09:34 UTC by jofrevalles

### Summary
Plot recipes currently describe plot primitives that live in an `Axis` but can not change the `Axis` parameters. Therefore, with plot recipes, we can't currently include `Colorbar`s, add interactions, and in general, customize the `Axis`.
In this PL we address #27, and we change the `plot` function so now it can take a `GridPosition` and plot into it. This enabled us to add the following features:
- Added integration to `plot` the contraction paths into subplots.
- Added the possibility to create 3D plots.
- Grids and decorations are removed by default in 2D plots.
- Two colorbars have been added that indicate the corresponding values of `flops` and `size`.

### Example
```julia
julia> using OptimizedEinsum
julia> using Makie
julia> using GLMakie
julia> output, inputs, size_dict = rand_equation(15, 4)
(Symbol[], [[:f, :e, :l, :s, :q], [:v, :D, :e, :u, :q, :i], [:w, :a, :y], [:C, :h, :A, :d, :c, :y, :m], [:x, :u], [:s, :g, :a, :d, :f, :l, :t], [:z, :C, :k, :j, :p, :b], [:r, :b], [:v, :m], [:D], [:n, :B], [:h, :w, :z, :t, :p], [:i, :k, :o], [:B, :n, :x], [:g, :r, :o, :A, :c, :j]], Dict(:o => 7, :b => 2, :p => 5, :n => 9, :j => 4, :e => 4, :D => 5, :B => 5, :c => 2, :h => 6…))
julia> path = contractpath(RandomGreedy, inputs, output, size_dict)
ContractionPath([(1, 6), (4, 9), (8, 15), (7, 12), (11, 14), (18, 13), (2, 10), (20, 5), (23, 22), (24, 16), (17, 3), (26, 19), (27, 21), (25, 28)], [[:f, :e, :l, :s, :q], [:v, :D, :e, :u, :q, :i], [:w, :a, :y], [:C, :h, :A, :d, :c, :y, :m], [:x, :u], [:s, :g, :a, :d, :f, :l, :t], [:z, :C, :k, :j, :p, :b], [:r, :b], [:v, :m], [:D], [:n, :B], [:h, :w, :z, :t, :p], [:i, :k, :o], [:B, :n, :x], [:g, :r, :o, :A, :c, :j]], Symbol[], Dict(:o => 7, :b => 2, :p => 5, :n => 9, :j => 4, :e => 4, :D => 5, :B => 5, :c => 2, :h => 6…))
julia> f = Figure(backgroundcolor="ivory", resolution=(1000, 700))
julia> scatter(f[1,1], 1..4, log)
Makie.AxisPlot(Axis (1 plots), Scatter{Tuple{Vector{Point{2, Float32}}}})
julia> lines(f[2,1], 1..10, cos)
Makie.AxisPlot(Axis (1 plots), Lines{Tuple{Vector{Point{2, Float32}}}})
julia> plot!(f[1:2,2:3], path; layout=Spring(dim=3))
Scene (1000px, 700px):
  0 Plots
  3 Child Scenes:
    ├ Scene (1000px, 700px)
    ├ Scene (1000px, 700px)
    └ Scene (1000px, 700px)
GridPosition(GridLayout[2, 3] (3 children), GridLayoutBase.Span(1:2, 2:3), GridLayoutBase.Inner())
```
![image](https://user-images.githubusercontent.com/61060572/216935831-932e283e-c552-4655-b840-7d087acb6997.png)

And we can also plot in 3D with:
```julia
julia> using NetworkLayout
julia> plot(path; layout=Spring(dim=3))
```
![image](https://user-images.githubusercontent.com/61060572/216936443-a3e340cc-1452-48fc-bd1e-eba711e9b6f1.png)

2023-02-06 09:58 UTC, mofeing commented
In the first plot, is the path plot a 3D plot?

2023-02-06 10:01 UTC, jofrevalles commented
> In the first plot, is the path plot a 3D plot?
Oh sorry, it was not, let me correct the code example.

2023-02-06 16:32 UTC, mofeing requested changes

2023-02-06 16:32 UTC, mofeing commented on src/Visualization.jl
> +    cbar = Colorbar(f[1,2], get_edge_plot(p), label=L"\log_{2}(size)", flip_vertical_label=true, labelsize = 34)
Remove the LatexStrings dependency.

```suggestion
    cbar = Colorbar(f[1,2], get_edge_plot(p), label="\\log\_\{2\}(size)", flip_vertical_label=true, labelsize = 34)
```

2023-02-06 16:32 UTC, mofeing commented on src/Visualization.jl
> +    cbar2 = Colorbar(f[1,0], get_node_plot(p), label=L"\log_{10}(flops)", flipaxis=false, labelsize = 34)
```suggestion
    cbar2 = Colorbar(f[1,0], get_node_plot(p), label="\\log\_\{10\}(flops)", flipaxis=false, labelsize = 34)
```

2023-02-06 16:32 UTC, mofeing commented on src/Visualization.jl
> +    cbar2 = Colorbar(f[1,0], get_node_plot(p), label=L"\log_{10}(flops)", flipaxis=false, labelsize = 34)
You may need to use `raw"..."` strings.

2023-02-06 16:32 UTC, mofeing commented on src/Visualization.jl
> +    if !isa(ax, LScene) # hide decorations if it is not a 3D plot
```suggestion
    # hide decorations if it is not a 3D plot
    if !isa(ax, LScene)
```

2023-02-06 16:32 UTC, mofeing commented on src/Visualization.jl
> +    cbar.alignmode = Mixed(left = -30, right = -10)
```suggestion
    # TODO configurable alignments
    cbar2.alignmode = Mixed(left = -10, right = -30)
    cbar.alignmode = Mixed(left = -30, right = -10)
```

2023-02-06 16:32 UTC, mofeing commented on src/Visualization.jl
> +    cbar = Colorbar(f[1,2], get_edge_plot(p), label=L"\log_{2}(size)", flip_vertical_label=true, labelsize = 34)
```suggestion
    # TODO configurable `labelsize`
    cbar = Colorbar(f[1,2], get_edge_plot(p), label=L"\log_{2}(size)", flip_vertical_label=true, labelsize = 34)
```

2023-02-06 16:36 UTC, jofrevalles commented on src/Visualization.jl
> +    haskey(kwargs, :layout) && isa(kwargs[:layout],Spring{3}) ? ax = LScene(f[1,1]) : ax = Axis(f[1,1])
Yes... I have to look into this

2023-02-06 16:39 UTC, mofeing commented on src/Visualization.jl
> +    haskey(kwargs, :layout) && isa(kwargs[:layout],Spring{3}) ? ax = LScene(f[1,1]) : ax = Axis(f[1,1])
btw, you can use `isa` as an infix operator like `kwargs[:layout] isa Spring{3}`

2023-02-06 16:47 UTC, mofeing commented
@jofrevalles I think it is failing in Code Coverage. can you check it out tomorrow?

2023-02-07 09:37 UTC, mofeing requested changes
I think these changes should fix the CI workflow. What I'm not sure is if we need to wrap everything between $ symbols like in LaTeX for equations.

2023-02-07 09:37 UTC, mofeing commented on src/Visualization.jl
> +    cbar = Colorbar(f[1,2], get_edge_plot(p), label="\\log\_\{2\}(size)", flip_vertical_label=true, labelsize = 34)
```suggestion
    cbar = Colorbar(f[1,2], get_edge_plot(p), label=raw"\log_{2}(size)", flip_vertical_label=true, labelsize = 34)
```

2023-02-07 09:37 UTC, mofeing commented on src/Visualization.jl
> +    cbar2 = Colorbar(f[1,0], get_node_plot(p), label="\\log\_\{10\}(flops)", flipaxis=false, labelsize = 34)
```suggestion
    cbar2 = Colorbar(f[1,0], get_node_plot(p), label=raw"\log_{10}(flops)", flipaxis=false, labelsize = 34)
```

2023-02-07 14:36 UTC, mofeing commented on src/Visualization.jl
> +    ax = current_axis(current_figure())
Isn't `ax` defined just a couple of lines above?

2023-02-07 14:36 UTC, mofeing commented on src/Visualization.jl
>      end
Integrate these lines with line 42?

2023-02-07 17:22 UTC, mofeing approved these changes

2023-02-07 17:23 UTC, merged